=== kannerjoker/Selenium_WebTours/target/classes/demoC3p0.xsd
<?xml version="1.0" ?>
<xsd:schema xmlns="http://www.demoC3p0.cn/c3p0-config" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.demoC3p0.cn/c3p0-config"
            elementFormDefault="qualified">
    <xsd:element name="c3p0-config" type="c3p0-configsType"/>
        <!-- 1 c3p0-config -->
        <xsd:complexType name="c3p0-configsType">
            <xsd:sequence>
                <xsd:element name="default-config" type="default-configType"/>
                <xsd:element name="named-config" type="named-configsType" minOccurs="1" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
        <!-- 2-1 default-config -->
        <xsd:complexType name="default-configType">
            <xsd:sequence>
                <xsd:element name="property" type="propertyType1" minOccurs="1" maxOccurs="7"/>
            </xsd:sequence>
            <xsd:attribute name="name" type="default_PropertyType"/>
        </xsd:complexType>
        <!-- 2-1-E1 property -->
        <xsd:complexType name="propertyType1">
            <xsd:simpleContent>
                <xsd:extension base="xsd:string">
                    <xsd:attribute name="name" type="nameType_1"></xsd:attribute>
                </xsd:extension>
            </xsd:simpleContent>
        </xsd:complexType>
        <!-- 2-1-A1  default_PropertyType-->
        <xsd:simpleType name="default_PropertyType">
            <xsd:restriction base="xsd:string"/>
        </xsd:simpleType>
        <!-- 2-1-E1-A1 -->
        <xsd:simpleType name="nameType_1">
            <xsd:restriction base="xsd:string">
                <xsd:enumeration value="classDriver"></xsd:enumeration>
                <xsd:enumeration value="jdbcUrl"></xsd:enumeration>
                <xsd:enumeration value="user"></xsd:enumeration>
                <xsd:enumeration value="password"></xsd:enumeration>
                <xsd:enumeration value="initialPoolSize"></xsd:enumeration>
                <xsd:enumeration value="maxPoolSize"></xsd:enumeration>
                <xsd:enumeration value="checkoutTimeout"></xsd:enumeration>
            </xsd:restriction>
        </xsd:simpleType>

        <!-- 2-2 named-config -->
        <xsd:complexType name="named-configsType">
            <xsd:sequence>
                <!-- 由于 default-config 与 named-config 的 property 定义方式相同,故将两个的type指定成一样-->
                <xsd:element name="property" type="propertyType1" minOccurs="1" maxOccurs="7"/>
            </xsd:sequence>
            <xsd:attribute name="name" type="nameType_2"/>
        </xsd:complexType>
        <!-- 2-2-A1 指定 named-config 的 name 属性 -->
        <xsd:simpleType name="nameType_2">
            <xsd:restriction base="xsd:string">
                <xsd:pattern value="new.*"></xsd:pattern>
            </xsd:restriction>
        </xsd:simpleType>

</xsd:schema>

=== kannerjoker/Selenium_WebTours/src/main/java/javaXml/xmls/demoC3p0.xml
<?xml version="1.0"?>
<c3p0-config
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://www.demoC3p0.cn/c3p0-config"
    xsi:schemaLocation="http://www.demoC3p0.cn/c3p0-config demoC3p0.xsd"
>
    <default-config name="default-config">
        <property name="classDriver">com.mysql.cj.jdbc.driver</property>
        <property name="jdbcUrl">jdbc:mysql://10.130.212.160</property>
        <property name="user">root</property>
        <property name="password">root</property>
        <property name="initialPoolSize">5</property>
        <property name="maxPoolSize">15</property>
        <property name="checkoutTimeout">2000</property>
    </default-config>
    <named-config name="newConfig">
        <property name="classDriver">com.mysql.cj.jdbc.driver</property>
        <property name="jdbcUrl">jdbc:mysql://10.130.212.131</property>
        <property name="user">kan</property>
        <property name="password">123456</property>
        <property name="initialPoolSize">8</property>
        <property name="maxPoolSize">18</property>
        <property name="checkoutTimeout">3000</property>
    </named-config>
</c3p0-config>
